version: '3'
services:
  scraper-db:
    build: ./db
    container_name: scraper-db
    ports:
      - 5432:5432

  scraper-server:
    build: ./server
    container_name: scraper-server
    depends_on:
      - scraper-db
    environment:
      WAIT_HOSTS: scraper-db:5432 
    env_file:
      - ./server/.env
    ports:
      - 4000:4000
    links:
      - scraper-db

  scraper-client:
    build: ./client
    container_name: scraper-client
    depends_on:
      - scraper-server
    ports:
      - 8080:8080
    links:
      - scraper-server
